import { Todo } from './todo';

export const TODOS: Todo[] = [
  {
    id: 1,
    title: 'Laver la vaisselle',
    content: 'Content todo 1',
    author: 'Martine',
    isCompleted: true,
    createdAt: new Date(),
    completedAt: null,
  },
  {
    id: 2,
    title: 'Faire un machine',
    content: 'Content todo 2',
    author: 'Martine',
    isCompleted: true,
    createdAt: new Date(),
    completedAt: null,
  },

  {
    id: 3,
    title: 'Sortir le linge',
    content: 'Content todo 3',
    author: 'Martine',
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
  },
  {
    id: 4,
    title: 'Faire a manger',
    content: 'Content todo 4',
    author: 'Martine',
    isCompleted: true,
    createdAt: new Date(),
    completedAt: null,
  },
  {
    id: 5,
    title: 'Mettre la table',
    content: 'Content todo 5',
    author: 'Martine',
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
  },
  {
    id: 6,
    title: "Passer l'aspi",
    content: 'Content todo 6',
    author: 'Martine',
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
  },
  {
    id: 7,
    title: 'Laver le sol',
    content: 'Content todo 7',
    author: 'Martine',
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
  },
  {
    id: 8,
    title: 'Aller chercher les enfants',
    content: 'Content todo 8',
    author: 'Martine',
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
  },
  {
    id: 9,
    title: 'Emmener Theo au judo',
    content: 'Content todo 9',
    author: 'Martine',
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
  },
  {
    id: 10,
    title: 'Rentrer',
    content: 'Content todo 10',
    author: 'Martine',
    isCompleted: false,
    createdAt: new Date(),
    completedAt: null,
  },
];
